[package]
name = "reth-zk-ress-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-zk-ress-protocol.workspace = true
reth-ress-provider.workspace = true
reth-primitives-traits.workspace = true
reth-storage-api.workspace = true
reth-errors.workspace = true
reth-evm.workspace = true
reth-ethereum-primitives.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# misc
eyre.workspace = true
tracing.workspace = true
