name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  conventional-title:
    name: Validate PR title is Conventional Commit
    runs-on: ubuntu-22.04
    steps:
      - name: Check title
        if: github.event_name == 'pull_request_target'
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
            test
            perf
            refactor
            docs
            ci
